name: Fetch and Process Release Asset

on:
  repository_dispatch:
    types: [triggered-by-release]

jobs:
  download-and-process-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Download the ZIP asset from repo1
        run: |
          repo_owner="li-albantrang"  # Propriétaire de repo1
          repo_name="test-routing"   # Nom de repo1
          RELEASE_TAG="${{ github.event.client_payload.version }}"

          echo "Téléchargement de l'asset depuis la release $RELEASE_TAG"

          # Télécharger l'asset ZIP
          gh release download $RELEASE_TAG \
            --repo $repo_owner/$repo_name \
            --pattern "release-registry.zip" \
            --dir ./downloaded-assets
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Unzip the downloaded asset
        run: |
          echo "Unzipping asset"
          mkdir -p ./unzipped-assets
          unzip ./downloaded-assets/release-registry.zip -d ./unzipped-assets

      - name: List files in unzipped directory
        run: |
          echo "Files in unzipped directory:"
          ls ./unzipped-assets
          ls -R ./unzipped-assets

      
       # Étape 4 : Remplacer les fichiers existants
      - name: Replace existing files with new ones
        run: |
          cp ./unzipped-assets/configs/immonet/live.yml configs/immonet/live/routings/live.yml
          cp ./unzipped-assets/configs/immonet/preview.yml configs/immonet/preview/routings/preview.yml
          cp ./unzipped-assets/configs/immonet/dev.yml configs/immonet/dev/routings/dev.yml
          cp ./unzipped-assets/configs/immoweb/live.yml configs/immoweb/live/routings/live.yml
          cp ./unzipped-assets/configs/immoweb/preview.yml configs/immoweb/preview/routings/preview.yml
          cp ./unzipped-assets/configs/immoweb/dev.yml configs/immoweb/dev/routings/dev.yml

      # Étape 5 : Créer une nouvelle branche et commit
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-routing-configs
          git add configs/
          git commit -m "Update routing configurations from release ${{ github.event.client_payload.version }}"

      # Étape 6 : Pousser la branche et créer une PR
      - name: Push branch and create PR
        run: |
          git push --set-upstream origin update-routing-configs
          gh pr create \
            --title "Update routing configurations from release ${{ github.event.client_payload.version }}" \
            --body "This PR updates the routing configurations from the latest release ${{ github.event.client_payload.version }} in repo1." \
            --base main \
            --head update-routing-configs
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
